# Generated by Django 5.2.1 on 2025-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
